<?php

/**
 * @file
 * Contains people_profiles.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;

/**
 * Implements hook_help().
 */
function people_profiles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.people_profiles':
      $output = '';
      $output .= '<h3>' . t('People Profiles') . '</h3>';
      $output .= '<p>' . t('This plugin module adds a content type named People Profiles.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements template_preprocess_node()
 */
function people_profiles_preprocess_node(&$variables, $hook)
{
  $node = $variables['node'];
  $default_people_profiles_page_view_mode = \Drupal::config('people_profiles.settings')->get('default_people_profiles_page_view_mode');

  if ($node->bundle() == 'people_profiles' && $variables['view_mode'] != 'full' && $variables['view_mode'] == $default_people_profiles_page_view_mode) {
    $variables['hidetitle'] = true;
  }


  if ($node->bundle() == 'people_profiles') {
    $default_parent_page_url = \Drupal::config('people_profiles.settings')->get('default_parent_page');
    $variables['people_profiles_url'] = $default_parent_page_url;
  }

  if($node->bundle() == 'people_profiles' && \Drupal::service('router.admin_context')->isAdminRoute()) {
    $variables['is_admin_route'] = true;
  }
}


/**
 * Implements hook_theme().
 */
function people_profiles_theme($existing, $type, $theme, $path) {

  //From the configuration get the default view mode
  $view_mode = 'full';
  if (\Drupal::config('people_profiles.settings')->get('default_people_profiles_page_view_mode') != null) {
    $view_mode = \Drupal::config('people_profiles.settings')->get('default_people_profiles_page_view_mode');
  }
  $template = 'node--people-profile--'. $view_mode;

  return [
   'node__people_profile__full' => [
      'template' => $template,
      'base hook' => 'node'
    ],
    'node__people_profile__teaser' => [
       'template' => 'node--people-profile--teaser',
       'base hook' => 'node'
     ],
     'node__people_profile__dsp_people_profiles' => [
        'template' => 'node--people-profile--dsp-people-profiles',
        'base hook' => 'node'
      ],
      'node__people_profile__wellness_people_profiles' => [
         'template' => 'node--people-profile--wellness-people-profiles',
         'base hook' => 'node'
       ],
      'node__people_profile__grad_div_featured_staff' => [
        'template' => 'node--people-profile--grad-div-featured-staff',
        'base hook' => 'node'
      ],
      'node__people_profile__people_profile_team_grid' => [
        'template' => 'node--people-profile--people-profile-team-grid',
        'base hook' => 'node'
      ],
      'node__people_profile__adp_people_profiles' => [
         'template' => 'node--people-profile--adp-people-profiles',
         'base hook' => 'node'
       ],
       'node__people_profile__staff_people_profiles' => [
         'template' => 'node--people-profile--staff_people_profiles',
         'base hook' => 'node'
       ],
        'node__people_profile__staff_team_grid' => [
         'template' => 'node--people-profile--staff-team-grid',
         'base hook' => 'node'
       ],
       'node__people_profile__staff_full_view' => [
         'template' => 'node--people-profile--staff-full-view',
         'base hook' => 'node'
       ],
  ];
}


/**
 * Implements hook_preprocess().
 */
function people_profiles_preprocess(&$variables, $hook) {
  $module_relative_url = \Drupal::service('extension.list.module')->getPath('people_profiles') . '/images/ucsb-logo.png';
  $module_absolute_url = \Drupal::service('file_url_generator')->generateAbsoluteString($module_relative_url);
  $variables['img_path'] = $module_absolute_url;
  $module_relative_url = \Drupal::service('extension.list.module')->getPath('people_profiles') . '/images/cloud.png';
  $module_absolute_url = \Drupal::service('file_url_generator')->generateAbsoluteString($module_relative_url);
  $variables['people_cloud_img_path'] = $module_absolute_url;
}

/**
 * Implements hook_entity_form_display_alter().
 */
function people_profiles_entity_form_display_alter(EntityFormDisplayInterface &$form_display, array $context)
{
  // use our custom form display for people_profiles
  if ($context['entity_type'] == 'node' && $context['bundle'] == 'people_profiles') {

    // Get the default_people_profiles_page_view_mode setting from the configuration 
    $view_mode = \Drupal::config('people_profiles.settings')->get('default_people_profiles_form_display_mode');

    if ($view_mode != null) {

      /** @var \Drupal\Core\Entity\EntityDisplayRepository $entity_display_repo */
      $entity_display_repo = \Drupal::service('entity_display.repository');
      $form_display = $entity_display_repo->getFormDisplay($context['entity_type'], $context['bundle'], $view_mode) ?: $form_display;
    }
  }
}


